.\" Man page for podshuffler-template
.\" Patrick Nance <jpnance@gmail.com>
.TH PODSHUFFLER-TEMPLATE 1 "2020-03-14" "1.0" "Podshuffler"
.SH NAME
podshuffler-template \- template a new podcast to your database
.SH SYNOPSIS
.B podshuffler template --help
.br
.B podshuffler template
.SH DESCRIPTION
This command allows you to do some cool things that I should tell you more about.
.SH OPTIONS
.PP
\fB--help\fR
.RS
Print help about the \fBpodshuffler-template\fR(1) command.
.RE
.PP
\fB--db\fR=<filename>
.RS
Use a specific file to keep track of all of your podcast data. If not specified, the default will be \fI$HOME/.local/share/podshuffler/podcasts.json\fR.
.RE
.PP
\fB--dry-run\fR
.RS
This will execute the add command as specified but not save anything to your database.
.RE
