.\" Man page for podshuffler-help
.\" Patrick Nance <jpnance@gmail.com>
.TH PODSHUFFLER-HELP 1 "2020-03-14" "1.0" "Podshuffler"
.SH NAME
podshuffler-help \- learn more about Podshuffler and its commands
.SH SYNOPSIS
.B podshuffler help
[command]
.SH DESCRIPTION
Without any arguments, this prints a list of Podshuffler commands (see \fBpodshuffler\fR(1)). If \fIcommand\fR is specified, more detailed information about that command will be shown.
.SH OPTIONS
.PP
command
.RS
Any one of the following: \fBadd\fR, \fBclean\fR, \fBedit\fR, \fBhelp\fR, \fBlist\fR, \fBmark\fR, \fBpull\fR, \fBpush\fR, \fBrefresh\fR, \fBremove\fR, and \fBstage\fR.
.RE
