.\" Man page for podshuffler
.\" Patrick Nance <jpnance@gmail.com>
.TH PODSHUFFLER 1 "2020-03-14" "1.0" "Podshuffler"
.SH NAME
podshuffler \- manage your podcasts and push them to a second-generation iPod Shuffle
.SH SYNOPSIS
.B podshuffler --help
.br
.B podshuffler
<command> [<args>]
.SH DESCRIPTION
Podshuffler is a command-line program that allows you to manage any number of podcast subscriptions and push the episodes to your second-generation iPod Shuffle.
.SH OPTIONS
.PP
\fB--help\fR
.RS
Print a list of Podshuffler commands you can use, described below.
.RE
.SH COMMANDS
.PP
\fBpodshuffler-add\fR(1)
.RS
Add a new podcast
.RE
.PP
\fBpodshuffler-clean\fR(1)
.RS
Remove unneeded podcast files from the staging area
.RE
.PP
\fBpodshuffler-edit\fR(1)
.RS
Modify the settings of an existing podcast
.RE
.PP
\fBpodshuffler-help\fR(1)
.RS
Show more information about a command
.RE
.PP
\fBpodshuffler-list\fR(1)
.RS
Show high-level podcast information
.RE
.PP
\fBpodshuffler-mark\fR(1)
.RS
Mark episodes as listened or unlistened
.RE
.PP
\fBpodshuffler-pull\fR(1)
.RS
Fetch and merge play data from the iPod Shuffle
.RE
.PP
\fBpodshuffler-push\fR(1)
.RS
Copy podcasts and control files to the iPod Shuffle
.RE
.PP
\fBpodshuffler-refresh\fR(1)
.RS
Fetch new episode information
.RE
.PP
\fBpodshuffler-remove\fR(1)
.RS
Remove an existing podcast
.RE
.PP
\fBpodshuffler-stage\fR(1)
.RS
Select and download episodes
.RE
