.\" Man page for podshuffler-list
.\" Patrick Nance <jpnance@gmail.com>
.TH PODSHUFFLER-LIST 1 "2020-03-14" "1.0" "Podshuffler"
.SH NAME
podshuffler-list \- output human-readable information about podcasts and episodes
.SH SYNOPSIS
.B podshuffler list --help
.br
.B podshuffler list
[\fB--db\fR <filename>] [\fB--podcast\fR <short name> [\fB--reverse\fR]]
.SH DESCRIPTION
Without any arguments, this will print out detailed information about every podcast in your Podshuffler database. If \fB--podcast\fR is specified, it will print out the same information for that podcast along with a list of every known episode of that podcast.
.SH OPTIONS
.PP
\fB--help\fR
.RS
Print help about the \fBpodshuffler-list\fR(1) command.
.RE
.PP
\fB--db\fR=<filename>
.RS
Use a specific file as your podcast database. If not specified, the default will be \fI$HOME/.local/share/podshuffler/podcasts.json\fR in the current directory.
.RE
.PP
\fB--podcast\fR=<short name>
.RS
A string matching the short name of the podcast you'd like to see more information about.
.RE
.PP
\fB--reverse\fR
.RS
If paired with \fB--podcast\fR, this will reverse the order of the episode list, making it reverse-chronological.
.RE
