.\" Man page for podshuffler-push
.\" Patrick Nance <jpnance@gmail.com>
.TH PODSHUFFLER-PUSH 1 "2020-03-14" "1.0" "Podshuffler"
.SH NAME
podshuffler-push \- copy podcasts from the staging area onto your iPod Shuffle
.SH SYNOPSIS
.B podshuffler push --help
.br
.B podshuffler push
[\fB--stage\fR <path>]
<iPod path>
.SH DESCRIPTION
This command will read the iTunesSD file from the staging path and copy any podcast episodes it requires, along with all of the iTunes files, to <iPod path>. Before doing that, it will also remove any unnecessary files (e.g. previously listened-to episodes) from <iPod path>.
.PP
Although \fB--dry-run\fR is not available, you can simulate the results of this command by specifying a regular directory as your <iPod Path>. Files will be copied over as usual but your iPod Shuffle will not be accessed.
.SH OPTIONS
.PP
\fB--help\fR
.RS
Print help about the \fBpodshuffler-push\fR(1) command.
.RE
.PP
\fB--stage\fR=<path>
.RS
A path to a Podshuffler staging area. The staging area is where \fBpodshuffler-stage\fR(1) downloads any podcast episodes it needs and rewrites iTunes-specific files that will later be pushed to your iPod Shuffle with \fBpodshuffler-push\fR(1). If not specified, the default will be \fIstage/\fR in the current directory. Any directory will work as long as the following three files exist within it, in their appropriate iTunes formats:
.IP \(bu 2
.I iPod_Control/iTunes/iTunesPState
.IP \(bu
.I iPod_Control/iTunes/iTunesSD
.IP \(bu
.I iPod_Control/iTunes/iTunesStats
.RE
.PP
<iPod path>
.RS
The path to your mounted iPod Shuffle. This will probably be something like \fI/media/username/IPODSHUFFLE\fR. Any directory (e.g. \fI./ipod/\fR) will work, if you'd like to do somewhat of a dry-run before copying to your iPod Shuffle.
.RE
